name: Akismet Module

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        php: [7.3, 7.4, 8.0, 8.1]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run php codesiffer
      run: vendor/bin/phpcs -s
      
    - name: Run tests
      env:
        TEST_APIKEY: ${{ secrets.TEST_APIKEY }}
        TEST_WEBSITE: ${{ secrets.TEST_WEBSITE }}
      run: vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml